# Generated by Django 4.2.28 on 2026-02-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file_size', models.FloatField(verbose_name='Размер (МБ)')),
                ('duration', models.FloatField(default=0, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата анализа')),
                ('results_json', models.JSONField(verbose_name='Полные результаты (JSON)')),
                ('threat_level', models.CharField(max_length=20, verbose_name='Уровень угрозы')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчет анализа',
                'verbose_name_plural': 'Отчеты анализа',
                'ordering': ['-created_at'],
            },
        ),
    ]
