# Generated by Django 4.2.28 on 2026-02-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='threat_level',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='total_threats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='file_size',
            field=models.FloatField(help_text='Размер в МБ'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='results_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
